name: Lint


on:
  push:
    paths:
      - '.github/workflows/lint.yml'
      - 'src/core/**/*.clj'
      - 'src/core/**/*.cljc'
      - 'src/core/**/*.cljs'
    branches:
      - master
  pull_request:
    branches:
      - master


env:
  clj-kondo-version: '2022.03.09'


jobs:
  clj-kondo:
    name: Lint with clj-kondo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup clj-kondo
        uses: DeLaGuardo/setup-clj-kondo@master
        with:
          version: ${{ env.clj-kondo-version }}
      - name: Lint
        run: |
          clj-kondo --lint src/core
          # --config .clj-kondo/config.edn
      - name: Discord action job digest notification
        if: always() # Pick up events even if the job fails or is canceled.
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: sarisia/actions-status-discord@v1
