name: Outdated CI


on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/outdated.yml'
      - 'deps.edn'
      - 'shadow-cljs.edn'
      - 'package.json'
    branches:
      - master
  pull_request:
    branches:
      - master


env:
  clojure-cli:
  java-version: "17"
  library: io.github.ajchemist/runner


jobs:
  outdated:
    if: "!(contains(github.event.head_commit.message, 'ci skip') || contains(github.event.head_commit.message, 'skip ci'))"
    runs-on: [ self-hosted, linux ]
    name: Check outdated deps
    steps:
      - uses: actions/checkout@v2
      - name: Cache local maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Cache gitlibs
        uses: actions/cache@v2
        with:
          path: ~/.gitlibs
          key: ${{ runner.os }}-gitlibs-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-gitlibs-
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: ${{ env.java-version }}
      - name: GPG settings and ci resource configuration
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --import
          mkdir -p $HOME/.m2
          gpg --decrypt .ci/settings.xml.asc > $HOME/.m2/settings.xml
      - name: Set up clojure-cli
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: ${{ env.clojure-cli }}
      - name: Outdated
        run: |
          clojure -M:slf4j-nop:outdated --skip=github-action --skip=pom --exclude=com.google.javascript/closure-compiler-unshaded
      - name: Discord action job digest notification
        uses: sarisia/actions-status-discord@v1
        if: always() # Pick up events even if the job fails or is canceled.
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
